
#include "../perf_event/perf.h"


uint64_t event_configs[NUM_EVENTS] = {
    PERF_COUNT_HW_CPU_CYCLES,
    PERF_COUNT_HW_INSTRUCTIONS,
    PERF_COUNT_HW_CACHE_MISSES,
    PERF_COUNT_HW_CACHE_REFERENCES,
    PERF_COUNT_HW_BRANCH_MISSES,
    PERF_COUNT_HW_BRANCH_INSTRUCTIONS
};