
#include "perf.h"


uint64_t hw_event_configs[NUM_HW_EVENTS] = {
    PERF_COUNT_HW_CPU_CYCLES,
    PERF_COUNT_HW_INSTRUCTIONS,
    PERF_COUNT_HW_CACHE_MISSES,
    PERF_COUNT_HW_CACHE_REFERENCES,
    PERF_COUNT_HW_BRANCH_MISSES,
    PERF_COUNT_HW_BRANCH_INSTRUCTIONS,
    // PERF_COUNT_HW_STALLED_CYCLES_FRONTEND,       // fixme: not supported on all architectures
    // PERF_COUNT_HW_STALLED_CYCLES_BACKEND         // fixme: not supported on all architectures
};

uint64_t sw_event_configs[NUM_SW_EVENTS] = {
    PERF_COUNT_SW_PAGE_FAULTS,
    PERF_COUNT_SW_CONTEXT_SWITCHES,
    PERF_COUNT_SW_CPU_MIGRATIONS,
    PERF_COUNT_SW_PAGE_FAULTS_MAJ,
    PERF_COUNT_SW_ALIGNMENT_FAULTS,
    PERF_COUNT_SW_EMULATION_FAULTS
};

uint64_t cache_event_configs[NUM_CACHE_EVENTS] = {
    PERF_COUNT_HW_CACHE_RESULT_ACCESS,
    PERF_COUNT_HW_CACHE_RESULT_MISS
};

uint64_t event_configs[NUM_EVENTS] = {
    PERF_COUNT_HW_CPU_CYCLES,
    PERF_COUNT_HW_INSTRUCTIONS,
    PERF_COUNT_HW_CACHE_MISSES,
    PERF_COUNT_HW_CACHE_REFERENCES,
    PERF_COUNT_HW_BRANCH_MISSES,
    PERF_COUNT_HW_BRANCH_INSTRUCTIONS,
    // PERF_COUNT_HW_STALLED_CYCLES_FRONTEND,       // fixme: not supported on all architectures
    // PERF_COUNT_HW_STALLED_CYCLES_BACKEND,        // fixme: not supported on all architectures
    // PERF_COUNT_SW_PAGE_FAULTS,
    // PERF_COUNT_SW_CONTEXT_SWITCHES,
    // PERF_COUNT_SW_CPU_MIGRATIONS,
    // PERF_COUNT_SW_PAGE_FAULTS_MAJ,
    // PERF_COUNT_SW_ALIGNMENT_FAULTS,
    // PERF_COUNT_SW_EMULATION_FAULTS,
    // PERF_COUNT_HW_CACHE_RESULT_ACCESS,
    // PERF_COUNT_HW_CACHE_RESULT_MISS
};
